<?php

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 */
function legalpro101_install() {
  // Disable visitor account creation.
  variable_set('user_register', USER_REGISTER_ADMINISTRATORS_ONLY);

  user_role_grant_permissions(DRUPAL_ANONYMOUS_RID, array('access content'));
  user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, array('access content'));
}
