#!/bin/bash
echo -e \n\n
echo `date` - $1
echo '----------------------------------------------------------------'


# Enable post install features
/srv/aegir/bin/drush -y @$1 en pro_101_support
/srv/aegir/bin/drush -y @$1 en pro_101_default_users

# Copy over default files
cp -R /srv/aegir/platforms/.profiles/pro_101/default_images/ /srv/aegir/platforms/$1/sites/$2/files/.
